 SELECT 문법 : 데이터 조회시 사용
 SELECT : 어떤거를 조회할건지? *: (all) 전부다 조회한다는 뜻
SELECT * FROM employees;
SELECT EMPLOYEE_ID FROM EMPLOYEES;


-- 실행순서
--1. FROM 실행 : 데이터를 먼저 가져와야함
--2. SELECT 실행 : 그 다음에 원하는 부분을 SELECT!


-- 부서테이블의 모든 정보를 출력
SELECT * FROM DEPARTMENTS;

-- 직원의 사번과 급여 정보 출력
SELECT EMPLOYEE_ID,SALARY FROM EMPLOYEES;

-- 사번,

SELECT EMPLOYEE_ID,FIRST_NAME,HIRE_DATE FROM EMPLOYEES;

-- 부서번호, 부서명, 부서위치번호를 출력
SELECT DEPARTMENT_ID,DEPARTMENT_NAME,LOCATION_ID FROM DEPARTMENTS;

-- 모든 직원의 연봉을 출력 해주세요
SELECT SALARY*12 FROM EMPLOYEES;

-- 별칭 붙여주기
SELECT SALARY*12 AS "YEAR_SALARY" FROM EMPLOYEES;

-- 직원의 입사일과 입사 다음날 
-- SELECT HIRE_DATE , HIRE_DATE+1 AS  "입사일","입사일 다음 날" FROM EMPLOYEES; 이러면 에러남!
SELECT HIRE_DATE AS "입사일", HIRE_DATE+1 AS "입사일 다음 날" FROM EMPLOYEES;

-- 줄바꿈 가능! ";" 콜론 덕분에 줄의 끝마침을 알아서 파악
SELECT HIRE_DATE AS "입사일", HIRE_DATE+1 AS "입사일 다음 날"
FROM EMPLOYEES;



INSERT INTO EMPLOYEES(EMPLOYEE_ID, LAST_NAME, EMAIL, HIRE_DATE, JOB_ID)
VALUES (207, '임', 'lim0606', SYSDATE,'IT_PROG');


SELECT * FROM EMPLOYEES;

-- WHERE절 : 테이블에 있는 "모든행에" 조건을 걸어주는 명령
-- 사번이 100인 직원의 FIRST_NAME 출력

SELECT FIRST_NAME FROM EMPLOYEES
WHERE EMPLOYEE_ID = 100;

-- 60번째 부서에서 근무하는 직원의 사번, 급여 출력

SELECT EMPLOYEE_ID,SALARY FROM EMPLOYEES
WHERE DEPARTMENT_ID = 60;

-- 급여가 5000이하인 사람들의 사번, FIRST_NAME,급여를 출력
SELECT EMPLOYEE_ID,FIRST_NAME,SALARY FROM EMPLOYEES
WHERE SALARY <=5000;

-- 연봉이 50000이상인 사람들의 사번, FIRST_NAME,연봉 출력
SELECT EMPLOYEE_ID,FIRST_NAME,SALARY*12 AS "연봉"  FROM EMPLOYEES
WHERE SALARY*12 >=50000;

-- 연봉이 50000이상인 사람들의 사번, FIRST_NAME,연봉 출력
-- 실행 순서상 WHERE가 SELECT 보다 먼저 실행되므로 에러가 발생
SELECT EMPLOYEE_ID,FIRST_NAME,SALARY*12 AS "연봉"  FROM EMPLOYEES
WHERE "연봉" >=50000;




-- JOB_ID가 'IT_PROG'인 직원의 사번, FIRST_NAME,JOB_ID 출력
SELECT EMPLOYEE_ID,FIRST_NAME,JOB_ID FROM EMPLOYEES
WHERE JOB_ID = 'IT_PROG';
-- 명령어는 대소문자 구분 안하지만, 값은 대소문자를 구분한다!
-- 따옴표와 쌍따옴표 구분함 > 데이터에 관련된 값을 조회할때는 ''를 써야함

-- JOB_ID가 'IT_PROG'이 아닌 직원의 사번, FIRST_NAME,JOB_ID 출력
SELECT EMPLOYEE_ID,FIRST_NAME,JOB_ID FROM EMPLOYEES
WHERE JOB_ID != 'IT_PROG';

-- 부서번호가 90이고, 급여가 5000이상인 직원의 사번, FIRST_NAM,E 급여 출력
SELECT EMPLOYEE_ID,FIRST_NAME,SALARY FROM EMPLOYEES
WHERE DEPARTMENT_ID =90 AND SALARY >=5000;

-- 100번째 부서에서 근무하거나 60번째 부서에서 근무하는 직원들의 사번, FIRST_NAME,부서번호 출ㄹ력
SELECT EMPLOYEE_ID,FIRST_NAME,DEPARTMENT_ID FROM EMPLOYEES
WHERE DEPARTMENT_ID = 100 OR DEPARTMENT_ID = 60;


-- jOB ID 가 IT_PROG이 아니고, FI_ACCOUNT가 아닌 직원들의 사번과  JOB_ID출력
SELECT EMPLOYEE_ID,JOB_ID FROM EMPLOYEES
WHERE JOB_ID != 'IT_PROG' AND JOB_ID !='FI_ACCOUNT';

-- 100번째 부서에서 근무하거나 50번째 부서에서 근무하는 직원중에서 연봉이 100000이상인 직원의 사번, FIRST_NAME,연봉출력
SELECT EMPLOYEE_ID,FIRST_NAME,SALARY*12 AS "연봉", DEPARTMENT_ID FROM EMPLOYEES
WHERE (DEPARTMENT_ID = 100 AND SALARY*12 >=100000) OR (DEPARTMENT_ID = 50 AND SALARY*12 >=100000);

-- 이 계산법이 문제 요구조건 + 더 간결한 내용인 것 같다!
SELECT EMPLOYEE_ID,FIRST_NAME,SALARY*12 AS "연봉", DEPARTMENT_ID FROM EMPLOYEES
WHERE (DEPARTMENT_ID = 100 OR DEPARTMENT_ID = 50) AND SALARY*12 >=100000;

-- 부서번호가 30,50,90 들 중 하나인 직원의 사번, 부서번호를 출력
SELECT EMPLOYEE_ID,DEPARTMENT_ID FROM EMPLOYEES
WHERE DEPARTMENT_ID = 30 OR DEPARTMENT_ID = 50 OR DEPARTMENT_ID = 90;


-- 코드가 너무 길어짐 > IN 연산 활용
-- IN :OR의 집합연산 
SELECT EMPLOYEE_ID,DEPARTMENT_ID FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (30,50,90 );

-- NOT을 붙이면 AND 연산으로 바뀜 > 30도 아니고, 50도 아니고, 90도 아님.
SELECT EMPLOYEE_ID,DEPARTMENT_ID FROM EMPLOYEES
WHERE DEPARTMENT_ID NOT IN (30,50,90 );

-- JOB_ID가 'AD_VP'이거나 'ST_MAN'인 사람의 FIRST_NAME,JOB_ID 를 출력

SELECT FIRST_NAME,JOB_ID FROM EMPLOYEES
WHERE JOB_ID IN ('AD_VP','ST_MAN');


-- MANAGER_ID가 145,146,147,148,149 가 아닌 직원 사번과 , MANGER_ID를 출력
SELECT EMPLOYEE_ID,MANAGER_ID FROM EMPLOYEES
WHERE MANAGER_ID NOT IN (145,146,147,148,149);

-- BETWEEN A AND B : 연속된 범위를 통해서 조건을 걸어줄 때 사용
-- 급여가 10000 대인 직원의 사번과 급여 출력
SELECT EMPLOYEE_ID, SALARY FROM EMPLOYEES
WHERE SALARY BETWEEN 10000 AND 19999;

-- 2005년도 입사 
SELECT FIRST_NAME, HIRE_DATE FROM EMPLOYEES
WHERE HIRE_DATE BETWEEN '05/01/01' AND '05/12/31';

-- 문자열 비교 검색 연산 
-- LIKE 연산과 %(글자수 제한 없음) , _(글자수 의미)
-- FIRST_NAME 'A'로 시작하는 직워들의 이름을 출력ㄱ
SELECT FIRST_NAME FROM EMPLOYEES
WHERE FIRST_NAME LIKE 'A%';

-- FIRST_NAME 'e'로 끝나는 직워들의 이름을 출력ㄱ
SELECT FIRST_NAME FROM EMPLOYEES
WHERE FIRST_NAME LIKE '%e';

-- FIRST_NAME 'e'가 들어간 직워들의 이름을 출력ㄱ
SELECT FIRST_NAME FROM EMPLOYEES
WHERE FIRST_NAME LIKE '%e%';


-- 
-- FIRST_NAME 'A'로 시작하는 이름이 4글자인 직워들의 이름을 출력ㄱ
SELECT FIRST_NAME FROM EMPLOYEES
WHERE FIRST_NAME LIKE 'A___';


-- FIRST_NAME에서 두번째 글자가 e인 사람의 이름을 출력
SELECT FIRST_NAME FROM EMPLOYEES
WHERE FIRST_NAME LIKE '_e%';

-- 이름이 'S'로 시작하고 'n'으로 끝나는 직원의 이름을 출력
SELECT FIRST_NAME FROM EMPLOYEES
WHERE FIRST_NAME LIKE 'S%n';

-- 1월에 입사한 직원의 사번과 입사일을 출력
SELECT EMPLOYEE_ID, HIRE_DATE FROM EMPLOYEES
WHERE HIRE_DATE LIKE '__/01/__';

SELECT EMPLOYEE_ID, HIRE_DATE FROM EMPLOYEES
WHERE HIRE_DATE LIKE '%/01/%';

SELECT EMPLOYEE_ID, HIRE_DATE FROM EMPLOYEES
WHERE HIRE_DATE LIKE '___01%';





