
-- 0226
-- ORDER BY : 특정 컬럼으로 정렬 (SELECT 의 구조 중 제일 마지막에 실행시킨다) > DEFAULT 오름차순(ASC)
SELECT DEPARTMENT_ID,MAX(SALARY*12) AS "최고연봉"
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING MAX(SALARY*12)>=100000
ORDER BY MAX(SALARY*12);

SELECT DEPARTMENT_ID,MAX(SALARY*12) AS "최고연봉"
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING MAX(SALARY*12)>=100000
ORDER BY 최고연봉;
--ORDER BY는 SELECT 보다 더 늦게 실행되므로 AS로 불러도 됨

-- 내림차순 정렬 (DESC)
SELECT DEPARTMENT_ID,MAX(SALARY*12) AS "최고연봉"
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING MAX(SALARY*12)>=100000
ORDER BY 최고연봉 DESC;


-- SELECT의 응용
-- JOIN : 두개 이상의 테이블에서 데이터를 조회하는 방법

-- 전직원의 FRIST_NAME, 부서이름을 출ㄹ력

-- 이렇게 코드를 작성하면 CROOS JOIN이 발생. 
-- CROSS JOIN : 두개의 테이블에서 모든 경우의 수로 데이터를 출력

-- JOIN 조건 : EMPLOYEE.DEPARTMENT_ID = DEPARTMENT.DEPARTMENT_ID
SELECT DEPARTMENT_NAME, FIRST_NAME,  EMPLOYEES.DEPARTMENT_ID
FROM DEPARTMENTS d,EMPLOYEES e --여기에 ALIAS를 붙여서 만들 수 있음.
WHERE DEPARTMENTS.DEPARTMENT_ID = EMPLOYEES.DEPARTMENT_ID;
-- DEPARTMENT_NAME, FIRST_NAME 은 각 테이블에 하나씩 밖에 없기 때문에 앞에 어떤 테이블인지 굳이 안적어줘도 됨





--1. 사번이 100인 직원의 FIRST_NAME, 부서 이름을 출력
-- 사번은 EMPLOYEES 테이블, 부서이름 DEPARTMENTS 테이블 > 둘다 불러내야함.

-- 처음 작성 코드 > 이렇게 작성하면 DEPARTMENT_NAME의 모든 이름이 다 출력되어버림
SELECT e.FIRST_NAME,d.DEPARTMENT_NAME FROM EMPLOYEES e ,DEPARTMENTS d
WHERE e.EMPLOYEE_ID=100;




SELECT e.FIRST_NAME,d.DEPARTMENT_NAME FROM EMPLOYEES e ,DEPARTMENTS d
WHERE (e.department_id = d.department_id) AND e.EMPLOYEE_ID=100;

-- 공통적으로 있는 곳을 묶어주는게 JOIN > 두개 테이블에 동일하게 있는 값으로 만ㄷ르어야함.




--2. 60번째 부서에서 근무하는 직원 중 5000이상의 급여를 받는 직원의 이름, 부서명, 급여 출력\

-- 처음 생각했던 프로세스 > GROUP BY로 묶어서 만들려고 했음.

SELECT e.FIRST_NAME,d.DEPARTMENT_NAME,e.SALARY,d.DEPARTMENT_ID 
FROM EMPLOYEES e ,DEPARTMENTS d
GROUP BY d.DEPARTMENT_ID =60
HAVING e.SALARY >=5000;


-- 두번째 작성 코드
SELECT e.FIRST_NAME,d.DEPARTMENT_NAME,e.SALARY,d.DEPARTMENT_ID 
FROM EMPLOYEES e ,DEPARTMENTS d
WHERE (d.DEPARTMENT_ID = 60) AND (e.SALARY>=5000);

-- 60번째 부서에서 근무하면서 급여를 6000이상 받아야함

-- 세번재 작성 코드 (EMPLOYEE 테이블과 DEPARTMENTS 테이블에서 JOIN을 해야햠))
SELECT e.FIRST_NAME,d.DEPARTMENT_NAME,e.SALARY,d.DEPARTMENT_ID 
FROM EMPLOYEES e ,DEPARTMENTS d
WHERE (d.DEPARTMENT_ID = 60) AND (e.SALARY>=5000) AND e.DEPARTMENT_ID = d.DEPARTMENT_ID;





--3. 각 부서의 부서장 (MANAGE)사번과, FIRST_NAME,급여, 부서이름을 출력해 주세요.

SELECT d.MANAGER_ID,e.FIRST_NAME,d.DEPARTMENT_NAME FROM EMPLOYEES e ,DEPARTMENTS d
WHERE (d.MANAGER_ID IS NOT NULL) AND (d.MANAGER_ID = e.EMPLOYEE_ID);

-- MANAGER ID, EMPLOYEE ID가 같은 사람이 각 부서의 부서장 !

SELECT * FROM DEPARTMENTS;
SELECT * FROM EMPLOYEES;

--4. DEPARTMENTS,LOCATIONS,COUNTRIES 테이블을 이용해서 
-- 각 부서 이름, 부서 위치 도시이름 (L.CITY), 나라이름 출력(C.COUNTRY_NAME)
-- D.LOACTION_ID
SELECT D.DEPARTMENT_NAME,L.CITY,C.COUNTRY_NAME FROM DEPARTMENTS D, LOCATIONS L,COUNTRIES C
WHERE (D.LOCATION_ID = L.LOCATION_ID) AND (L.COUNTRY_ID = C.COUNTRY_ID);


-- JOIN조건 개수는 테이블 개수 -1 개 만큼 항상 필요함. >
-- 테이블 개수가 많아지면 많아질수록 JOIN 조건의 개수가 늘어나고, 

SELECT * FROM DEPARTMENTS;
SELECT * FROM LOCATIONS;
SELECT * FROM COUNTRIES;

-- SUB QUERY
-- 이름이 NEENA인 직원과 같은 부서에서 근무하는 직원들의 FIRST_NAME, 급여, 부서번호 출력

SELECT E.FIRST_NAME,E.SALARY,E.DEPARTMENT_ID FROM EMPLOYEES E
WHERE E.DEPARTMENT_ID = 90;

-- NEENA의 부서번호를 구해주세요
SELECT DEPARTMENT_ID 
FROM EMPLOYEES
WHERE FIRST_NAME = 'Neena';


-- 밑에 쿼리문을 통해서 (NEENA의 부서번호를 구하는 쿼리) 를통해서 위에 90에 해당하는 곳에 넣어줌

SELECT E.FIRST_NAME,E.SALARY,E.DEPARTMENT_ID FROM EMPLOYEES E
WHERE E.DEPARTMENT_ID =(SELECT DEPARTMENT_ID 
FROM EMPLOYEES
WHERE FIRST_NAME = 'Neena')
;

-- 쿼리문 안에 또다른 쿼리문을 넣어서 먼저 실행시킬 쿼리를 ()안에 넣어서 만들어준다!

