-- (0227)
-- 서브쿼리 : 쿼리문안에서 사용하는 또다른 쿼리문
SELECT * FROM DEPARTMENTS;
SELECT * FROM EMPLOYEES;



-- 1. FISRT_NAME 이 "SHELLI'인 직원보다 급여가 낮은 직원의 이름 , 급여 출력 
SELECT FIRST_NAME,SALARY FROM EMPLOYEES
WHERE SALARY < (SELECT SALARY FROM EMPLOYEES
                WHERE FIRST_NAME = 'Shelli');

SELECT SALARY FROM EMPLOYEES
    WHERE FIRST_NAME = 'Shelli';

-- 2. NANCY보다 빨리 입사한 직워느이 사번과 이름, 입사일을 출력 
SELECT EMPLOYEE_ID,FIRST_NAME,HIRE_DATE  FROM EMPLOYEES
WHERE HIRE_DATE <(SELECT HIRE_DATE FROM EMPLOYEES
                    WHERE FIRST_NAME = 'Nancy');

SELECT HIRE_DATE FROM EMPLOYEES
WHERE FIRST_NAME = 'Nancy';

-- 3. 전직원의 평균급여보다 더 많이 받는 직원의 이름, 급여를 출력
SELECT FIRST_NAME,SALARY FROM EMPLOYEES
WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES);


-- 4. 'IT'부서에서 근무하는 직원의 사번, 이름, 부서번호

SELECT EMPLOYEE_ID,FIRST_NAME,DEPARTMENT_ID FROM EMPLOYEES
WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID FROM DEPARTMENTS
WHERE DEPARTMENT_NAME = 'IT');


-- JOIN 활용
SELECT E.EMPLOYEE_ID, E.FIRST_NAME, E.DEPARTMENT_ID FROM EMPLOYEES E, DEPARTMENTS D
WHERE (E.DEPARTMENT_ID = D.DEPARTMENT_ID) AND D.DEPARTMENT_NAME = 'IT' ;


-- 모든 서브쿼리문은 JOIN으로 / JOIN문은 서브쿼리문으로 


-- 실습2
-- 1. 'IT'부서와 'SALES'부서에서 근무하는 직원들의 사번,이름,급여, 부서번호 출력

SELECT EMPLOYEE_ID,FIRST_NAME,SALARY, DEPARTMENT_ID FROM EMPLOYEES
WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID FROM DEPARTMENTS
WHERE DEPARTMENT_NAME = 'IT' OR  'Sales');

-- 위 코드처럼 작성하면 서브쿼리로 얻어진 값이 2개가 들어가 버리므로 따로따로 작성해줘야함
-- 왜냐하면 WHERE은 한 행씩 비교하기 때문에
  
-- 내가 생각했던 코드.
SELECT EMPLOYEE_ID,FIRST_NAME,SALARY, DEPARTMENT_ID FROM EMPLOYEES
WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID FROM DEPARTMENTS
WHERE DEPARTMENT_NAME = 'IT') OR DEPARTMENT_ID = (SELECT DEPARTMENT_ID FROM DEPARTMENTS
WHERE DEPARTMENT_NAME = 'Sales');

-- 다른 코드 IN을 활용
SELECT EMPLOYEE_ID,FIRST_NAME,SALARY, DEPARTMENT_ID FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID FROM DEPARTMENTS
WHERE DEPARTMENT_NAME = 'IT' OR  DEPARTMENT_NAME = 'Sales');

-- 2. LAST_NAME이 'KING' 또는 'KOCHHAR'인 직원들과 같은 부서에서 근무하는 직원의 사번, FIRST_NAME, 부서번호 출력

-- 2.1 EMPLOYEES에서 LAST_NAME이 'King' / 'Kochhar'인 사람의 부서번호를 찾아서
SELECT DEPARTMENT_ID FROM EMPLOYEES
                        WHERE LAST_NAME = 'King' OR LAST_NAME = 'Kochhar';

-- 2.2 부서ID 비교를 통해
SELECT EMPLOYEE_ID,FIRST_NAME,DEPARTMENT_ID FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID FROM EMPLOYEES
                        WHERE LAST_NAME = 'King' OR LAST_NAME = 'Kochhar');




-- 3. IT부서의 직원들과 같은 급열를 받는 직원의 사번, 이름 급여, 부서번호

-- 3.1 IT부서 직원들의 급여를 확인하는 코드. > 부서 이름이 DEPARTMENTS 테이블에 있고
-- DEPARMENT_ID로 JOIN해서 IT직원들의 SALARY를 파악
SELECT E.SALARY FROM EMPLOYEES E,DEPARTMENTS D
WHERE D.DEPARTMENT_NAME ='IT' AND D.DEPARTMENT_ID = E.DEPARTMENT_ID;

-- 3.2 그런 다음 SALARY를 IN 연산을 통해, 서브쿼리로 작성하면 된다
SELECT EMPLOYEE_ID,FIRST_NAME,DEPARTMENT_ID,SALARY
FROM EMPLOYEES
WHERE SALARY IN (SELECT E.SALARY FROM EMPLO YEES E,DEPARTMENTS D
                    WHERE D.DEPARTMENT_NAME ='IT' AND D.DEPARTMENT_ID = E.DEPARTMENT_ID);
           
           
           
                    
-- 4. 각 부서별 최고 급여를 받는 직원의 사번, 이름, 급여, 부서번호를 출력

-- 4.1 각 부서의 최고 급여를 파악
SELECT EMPLOYEE_ID,DEPARTMENT_ID, MAX(SALARY) FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;
-- EMPLOYEE_ID를 누구를 추출할지 알 수 없음


-- 4.2 해당하는 직원의 사번, 이름, 급여, 부서번호 출력                   
SELECT EMPLOYEE_ID,FIRST_NAME,SALARY,DEPARTMENT_ID FROM EMPLOYEES
WHERE SALARY IN (SELECT MAX(SALARY) FROM EMPLOYEES
                    GROUP BY DEPARTMENT_ID);
-- 이렇게 하면 각 그룹별이 아니라 샐러리가 똑같은 사람들을 모두를 추출
                    
SELECT EMPLOYEE_ID,FIRST_NAME,SALARY,DEPARTMENT_ID FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;
-- 이렇게가 안되는 이유가 DEPARTMENT_ID 에서 GROUP BY 별로 하면 누구를 뽑아야할지 모름.


SELECT EMPLOYEE_ID,FIRST_NAME,SALARY,DEPARTMENT_ID FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID, MAX(SALARY) FROM EMPLOYEESGROUP BY DEPARTMENT_ID)    
GROUP BY DEPARTMENT_ID
HAVING SALARY = (SELECT MAX(SALARY) FROM EMPLOYEES
                    GROUP BY DEPARTMENT_ID);
--                     

SELECT EMPLOYEE_ID,FIRST_NAME,SALARY,DEPARTMENT_ID FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID, MAX(SALARY) FROM EMPLOYEES GROUP BY DEPARTMENT_ID);                 
                    
                    
-- 각 부서별 최고금액을 추출                    
SELECT DEPARTMENT_ID, MAX(SALARY) FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;        
-- 해당 테이블과 JOIN해야하나?\


-- 다시 : 각 부서별 최고금액을 가지는 사람의 EMPLOYEE_ID를 찾기
SELECT DEPARTMENT_ID, MAX(SALARY) FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

SELECT EMPLOYEE_ID,FIRST_NAME,SALARY,DEPARTMENT_ID FROM EMPLOYEES
WHERE (DEPARTMENT_ID IN (SELECT DEPARTMENT_ID FROM EMPLOYEES
GROUP BY DEPARTMENT_ID)) AND (SALARY IN (SELECT MAX(SALARY) FROM EMPLOYEES
GROUP BY DEPARTMENT_ID));

-- 원래 코드랑 똑같은 결과...
-- 가장 마지막 코드는 어차피 정해져있음.
-- 이 안의 조건문을 "각 부서ㅓ별 최고금액을 가지는 부서아이디와 최고금액" 과 어떻게ㅐ 연결 시킬 것인지가 중요.

SELECT EMPLOYEE_ID,FIRST_NAME,SALARY,DEPARTMENT_ID FROM EMPLOYEES;



-- 정답...> 그냥 DEPARTMENT_ID 까지 함께 넣어서 비교하면 됐음...
SELECT EMPLOYEE_ID,FIRST_NAME,SALARY,DEPARTMENT_ID
FROM EMPLOYEES
WHERE (SALARY,DEPARTMENT_ID) IN (SELECT MAX(SALARY),DEPARTMENT_ID
                                FROM EMPLOYEES
                                GROUP BY DEPARTMENT_ID);        



-- 값의 크기를 비교해주는 연산자
-- 'IT' 부서의 급여보다 더 많이 받는 직원의 이름, 급여, 부서번호를 출력


-- 이건 IT부서의 평균 급여보다 많이 받는 직원
SELECT FIRST_NAME,SALARY,DEPARTMENT_ID FROM EMPLOYEES
WHERE SALARY > (SELECT AVG(E.SALARY) FROM EMPLOYEES E,DEPARTMENTS D
                WHERE D.DEPARTMENT_NAME ='IT' AND D.DEPARTMENT_ID = E.DEPARTMENT_ID);


SELECT FIRST_NAME,SALARY,DEPARTMENT_ID FROM EMPLOYEES
WHERE SALARY >(SELECT MIN(E.SALARY) FROM EMPLOYEES E,DEPARTMENTS D
                WHERE D.DEPARTMENT_NAME ='IT' AND D.DEPARTMENT_ID = E.DEPARTMENT_ID);



-- ANY, ALL 크기 비교연산
-- ANY : 하나라도 만족하면 출력
-- ALL : 모두 다 만족행야 출력

SELECT FIRST_NAME,SALARY,DEPARTMENT_ID FROM EMPLOYEES
WHERE SALARY >ANY(SELECT E.SALARY FROM EMPLOYEES E,DEPARTMENTS D
                WHERE D.DEPARTMENT_NAME ='IT' AND D.DEPARTMENT_ID = E.DEPARTMENT_ID);
-- 위 코드와 완전히 동일함
SELECT FIRST_NAME,SALARY,DEPARTMENT_ID FROM EMPLOYEES
WHERE SALARY >(SELECT MIN(E.SALARY) FROM EMPLOYEES E,DEPARTMENTS D
                WHERE D.DEPARTMENT_NAME ='IT' AND D.DEPARTMENT_ID = E.DEPARTMENT_ID);

SELECT FIRST_NAME,SALARY,DEPARTMENT_ID FROM EMPLOYEES
WHERE SALARY >ALL(SELECT E.SALARY FROM EMPLOYEES E,DEPARTMENTS D
                WHERE D.DEPARTMENT_NAME ='IT' AND D.DEPARTMENT_ID = E.DEPARTMENT_ID);
-- 위 코드와 완전히 동일함                
SELECT FIRST_NAME,SALARY,DEPARTMENT_ID FROM EMPLOYEES
WHERE SALARY >(SELECT MAX(E.SALARY) FROM EMPLOYEES E,DEPARTMENTS D
                WHERE D.DEPARTMENT_NAME ='IT' AND D.DEPARTMENT_ID = E.DEPARTMENT_ID);



-- JOB ID가 'AC_ACCOUNT'인 직원 전원보다 급여가 낮은 직워느이 이름, 급여를 출력
SELECT FIRST_NAME,SALARY FROM EMPLOYEES
WHERE SALARY < ALL (SELECT SALARY 
                    FROM EMPLOYEES
                    WHERE JOB_ID = 'AC_ACCOUNT');


-- 30번 부서직원의 급여중에서 한명이라도 높은 급여를 
SELECT EMPLOYEE_ID,SALARY,DEPARTMENT_ID FROM EMPLOYEES
WHERE SALARY > ANY(SELECT SALARY FROM EMPLOYEES
                    WHERE DEPARTMENT_ID = 30);


SELECT SALARY FROM EMPLOYEES
WHERE DEPARTMENT_ID = 30;
